version: 2

plugins:
  eslint:
    enabled: true

checks:
  argument-count:
    config:
      threshold: 6
  file-lines:
    config:
      threshold: 300
  method-count:
    config:
      threshold: 40
  method-complexity:
      config:
        threshold: 10
  identical-code:
      config:
        threshold: 100
  similar-code:
      enabled: false

exclude_patterns:
- "coverage/**/*"
- "dev_browser/**/*"
- "dist/**/*"
- "documentation/**/*"
- "groups/**/*"
- "misc/**/*"
- "node_modules/**/*"
- "plato/**/*"
- "routes/**/*"
- "test/**/*"
- "jsdoc_plugin/**/*"
- "index.js"
- "app.js"
- "gulpfile.js"
- "gulp.config.js"
- "wallaby.js"
- "jsdoc.conf.json"

ratings:
  paths:
  - "src/**/*"