engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 130
  fixme:
    enabled: false
  nodesecurity:
    enabled: false

exclude_paths:
- "coverage/**/*"
- "dev_browser/**/*"
- "dist/**/*"
- "documentation/**/*"
- "groups/**/*"
- "misc/**/*"
- "node_modules/**/*"
- "plato/**/*"
- "routes/**/*"
- "test/**/*"
- "jsdoc_plugin/**/*"
- "index.js"
- "app.js"
- "gulpfile.js"
- "gulp.config.js"
- "wallaby.js"
- "jsdoc.conf.json"

ratings:
  paths:
  - "src/**/*"