language: "node_js"

cache:
  directories:
    - "node_modules"

node_js:
  - "5"
  - "6"
  - "7"
  - "iojs"

script: "npm run lint:test"

after_success:
- "npm run documentation"
- "npm run coverage:report"
- "npm bundle:minify"

after_script:
- "npm install -g codeclimate-test-reporter"
- "codeclimate-test-reporter < coverage/lcov.info"

branches:
  only:
  - "develop"
  - "master"

addons:
  code_climate:
    repo_token: "88f6338a30b9b3b63e26685f78c813c4ca0448d6e21b7f2fed6878ccc11e7f47"