language: node_js

cache:
  directories:
    - node_modules

before_install:
  - npm -i

node_js:
  - "4"
  - "5"
  - "6"
  - "7"

script: npm test

after_success:
  - npm run coverage-report

after_script:
  - "npm install -g codeclimate-test-reporter"
  - "codeclimate-test-reporter < coverage/Chrome*.lcov.info"

branches:
  only:
    - "develop"
    - "master"

addons:
  code_climate:
    repo_token: