language: "node_js"

cache:
  directories:
    - "node_modules"

node_js:
  - "6"
  - "7"

script:
- "npm run lint:test"

after_success:
- "npm run coverage"

after_script:
- "npm install -g codeclimate-test-reporter"
- "codeclimate-test-reporter < ./coverage/lcov.info"

branches:
  only:
  - "develop"
  - "master"